name: ${project.artifactId}
main: org.swallowmc.AdvancementTranslate.AdvancementTranslate
version: ${project.version}
website: ${project.url}
api-version: 1.16
author: ${project.organization.name}
depend: [PlaceholderAPI]